export default [
    {
        title: "Breaking Barriers: LogZilla Hits 5M Events Per Second, Achieving Unprecedented Performance",
        slug: "breaking-log-and-siem-barriers-logzilla-achieves-unprecedented-5m-events-per-second",
        author: "cdukes",
        category: "news",
        meta_description: "Discover how LogZilla is redefining the landscape of log management by achieving an unprecedented 5 million events per second, setting a new industry benchmark.",
        meta_title: "Breaking Barriers: LogZilla Hits 5M Events Per Second",
        reading_time: "6",
        keywords: "Log management solutions, High-speed data processing, Event processing scalability, Network efficiency optimization",
        tags: "it-operations; log-analysis; log-management; logzilla; machine-learning; netops; performance; scalability; siem; technology",
        created_date: "2024-04-29",
        updated_date: "2024-05-01",
        published_date: "2024-05-01",
        background_image: "images/background_960x540.png",
        banner_image: "images/banner_1600x500.png",
        half_width_image: "images/half_width_700x540.png",
        thumbnail_image: "images/thumbnail_300x300.png",
        opengraph_image: "images/opengraph_1200x630.png"
    },
    {
        title: "Unlock the Power of Centralized Log Management: LogZilla as a Pre-processor for SIEM Tools",
        slug: "benefits-of-using-a-centralized-log-manager-as-a-pre-processor-to-siem-tools",
        author: "cdukes",
        category: "itops",
        meta_description: "Discover the benefits of using LogZilla as a pre-processor for your SIEM tool, including improved efficiency, cost savings, and enhanced threat detection.",
        meta_title: "Boost Your SIEM Efficiency with LogZilla as a Pre-processor",
        reading_time: "3",
        keywords: "log management, LogZilla, SIEM integration, log deduplication, long-term storage, metadata enrichment, incident response, security analytics",
        tags: "siem; syslog",
        created_date: "2023-03-03",
        updated_date: "2024-05-15",
        published_date: "2024-05-15",
        background_image: "images/background_1920x1080.webp",
        banner_image: "images/banner_1600x499.webp",
        half_width_image: "images/half_width_700x545.webp",
        thumbnail_image: "images/thumbnail_900x900.webp",
        opengraph_image: "images/opengraph_1200x630.jpg"
    },
    {
        title: "Uncovering Hidden Network Issues with LogZilla: A Sales Perspective",
        slug: "application-performance-degradation",
        author: "pwillis",
        category: "itops",
        meta_description: "Learn how LogZilla helps a salesperson identify complex network issues and improve IT triage, even without an extensive technical background.",
        meta_title: "Uncover Network Issues with LogZilla: Sales Insights",
        reading_time: "1",
        keywords: "LogZilla, network issues, sales perspective, log data analysis, network dashboard, IT triage, log management",
        tags: "netops; scalability; performance",
        created_date: "2021-12-10",
        updated_date: "2023-04-05",
        published_date: "2023-04-05",
        background_image: "images/background_960x540.webp",
        banner_image: "images/banner_1600x499.webp",
        half_width_image: "images/half_width_700x540.webp",
        thumbnail_image: "images/thumbnail_300x300.webp",
        opengraph_image: "images/opengraph_1200x630.jpg"
    },
   
];